'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
   return queryInterface.bulkInsert(
     "Spots",
     [
       {
         name: "Olympus Mons",
         photos:
           "https://cdn.mos.cms.futurecdn.net/XNRcoHujh5mZHmPQZzYbgH.jpg https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Olympus_Mons_alt.jpg/800px-Olympus_Mons_alt.jpg https://lowell.edu/wp-content/uploads/2020/09/maxresdefault.jpg https://designyoutrust.com/wp-content/uploads/2020/09/1-36.jpg https://astronomy.com/-/media/Images/News%20and%20Observing/News/2020/11/DSCCR1116_15.jpg?mw=600",
         price: 500,
         avg_Rating: 4.94,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
         system: "Milky Way",
         planet: "Mars",
         region: "Mountains",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Omega Station",
         photos:
           "https://d2pn8kiwq2w21t.cloudfront.net/images/jpegPIA21943.width-1024.jpg https://cdn.mos.cms.futurecdn.net/JhUbTTqmevd4h6dBGg9vzG.png https://images.fineartamerica.com/images-medium-large-5/futuristic-space-station-stefan-schiesslscience-photo-library.jpg https://c4.wallpaperflare.com/wallpaper/978/502/452/sci-fi-space-station-futuristic-moon-space-hd-wallpaper-preview.jpg https://i.pinimg.com/originals/27/c1/4f/27c14feb4b9036cf0ec8ff399f9407b3.jpg https://c4.wallpaperflare.com/wallpaper/21/1003/810/futuristic-space-station-paul-chadeisson-space-wallpaper-preview.jpg",
         price: 800,
         avg_Rating: 4.78,
         arrangements: "Room",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
         system: "Saturnalia Clusters",
         planet: "Omega",
         region: "Virgo Nebula",
         hostId: 2,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Tanaan Jungles",
         photos:
           "https://www.telegraph.co.uk/content/dam/Travel/2018/September/El-Yunque-morning-mist-iStock-535499464.jpg backend/db/images/jungle3.jpg backend/db/images/jungle2.jpeg",
         price: 2200,
         arrangements: "Cabin",
         avg_Rating: 4.61,
         description: "desc",
         system: "Kepler 425ger",
         planet: "Osiris",
         region: "Timorin",
         hostId: 2,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Cliffs of Dover",
         photos:
           "https://solarsystem.nasa.gov/system/resources/detail_files/812_PIA00080.jpg https://solarsystem.nasa.gov/resources/811/global-callisto-in-color/?category=planets_jupiter https://solarsystem.nasa.gov/resources/813/ganymede-bright-and-dark-terrain/?category=planets_jupiter https://solarsystem.nasa.gov/resources/930/parade-of-planets/?category=planets_jupiter https://solarsystem.nasa.gov/resources/810/ios-pele-hemisphere-after-pillan-changes/?category=planets_jupiter",
         price: 1100,
         arrangements: "Tent",
         avg_Rating: 4.36,
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
         system: "Saturnalia Clusters",
         planet: "Omega",
         region: "Virgo Nebula",
         hostId: 2,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Mount Calamine",
         photos:
           "https://solarsystem.nasa.gov/system/resources/detail_files/738_PIA22337-16.jpg https://solarsystem.nasa.gov/system/resources/detail_files/737_PIA22336-16.jpg https://solarsystem.nasa.gov/system/resources/detail_files/736_PIA22335-16.jpg https://solarsystem.nasa.gov/system/resources/detail_files/2297_IMG_5580_800.jpg https://solarsystem.nasa.gov/system/resources/detail_files/2441_PIA21033.jpg",
         price: 3800,
         avg_Rating: 4.66,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
         system: "Saturnalia Clusters",
         planet: "Omega",
         region: "Virgo Nebula",
         hostId: 2,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Station Eris",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         avg_Rating: 4.78,
         description: "desc",
         system: "Milky Way",
         arrangements: "Room",
         planet: "Jupiter",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "City of New Atlantis",
         photos:
           "https://wallpaperaccess.com/full/318352.jpg https://wallpaperaccess.com/full/318351.jpg https://d2pn8kiwq2w21t.cloudfront.net/images/jpegPIA24470.width-1600.jpg https://static7.depositphotos.com/1224164/722/i/600/depositphotos_7225316-stock-photo-city-futuristic-landscape.jpg https://lh3.googleusercontent.com/proxy/WVFFkA-GpLwkYkP0_O3apleXZQAXdzNIbNVfHRAWsfKko6J1cpHFK32u3OF2qT2R1pGgOu-ZbZ139687c1p_cY017CIM2vFvP-7Wi-BI7s1m1q1DcUb5ZHfU0qXxSXe8tfg ",
         price: 800,
         avg_Rating: 4.78,
         arrangements: "Apartment",
         description: "desc",
         system: "Voyager",
         planet: "Altahe",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Xinjiang Temple",
         photos:
           "https://ak.picdn.net/shutterstock/videos/1011772808/thumb/1.jpg https://cdn1.epicgames.com/ue/product/Screenshot/14-1920x1080-5c79660d8fec78590396861e32e8aee3.jpg?resize=1&w=1600 https://i.pinimg.com/originals/bd/1c/36/bd1c36ab867bce0ae9701d16dda93506.jpg https://previews.123rf.com/images/scottff72/scottff721708/scottff72170800012/83702365-futuristic-space-station-interior-overlooking-a-planet-with-a-center-atrium-3d-rendering.jpg https://cdn.pocket-lint.com/r/s/1200x/assets/images/142554-gadgets-feature-space-station-concept-images-image1-ymal9hdvfx.jpg ",
         price: 200,
         avg_Rating: 4.61,
         arrangements: "Room",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
         system: "Sol",
         planet: "Jupiter",
         region: "Exolayer",
         hostId: 3,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "New Austin",
         photos:
           "https://www.marssociety.org/wp-content/uploads/2020/02/elon-musk-mars-city-cost-10-trillion-1200x630-1.jpg https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/abiboo-nuwa-cliff-and-valley-1616610379.png?crop=1.00xw:1.00xh;0,0&resize=640:* https://fastly.syfy.com/sites/syfy/files/styles/1200x680/public/2020/06/msc1.jpg?offset-x=33&offset-y=0 https://www.3blmedia.com/sites/www.3blmedia.com/files/images/Still_Rendering_GPURendered_ArchCivilEng_Misirdzhiev.jpg https://wp-assets.futurism.com/2020/02/this-group-is-collecting-designs-for-a-martian-city.jpg",
         price: 400,
         arrangements: "Apartment",
         avg_Rating: 4.91,
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
         system: "Mars",
         planet: "Jupiter",
         region: "Exolayer",
         hostId: 3,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Hope",
         photos:
           "https://wallpaperaccess.com/full/318350.jpg https://www.sukhbeerbrar.com/en/wp-content/uploads/2021/03/1616392384_292_Nuwa-Mars-First-City-The-city-of-dreams-will-settle.jpg https://www.greenprophet.com/wp-content/uploads/mars-city.jpg https://static.dezeen.com/uploads/2021/04/mars-city-capital-abiboo_dezeen_2364_col_0.jpg https://qph.fs.quoracdn.net/main-qimg-defec1e1f21575acee236cdf95b56eed",
         price: 400,
         avg_Rating: 4.75,
         arrangements: "Apartment",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
         system: "Milky Way",
         planet: "Mars",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Station Caseil",
         photos:
           "https://i.pinimg.com/originals/26/c9/48/26c9489d70e7ed543e99cb3e29eed25e.jpg https://external-preview.redd.it/iIFnLm7wZDvm9N1fRgKtk8TIzTpeKQVfVx9Apjt5W1E.jpg?auto=webp&s=3c900222e5e458013a9f5df9801a739463b03044 https://media.istockphoto.com/photos/futuristic-architecture-scifi-corridor-interior-in-space-station-with-picture-id1223695638?k=6&m=1223695638&s=170667a&w=0&h=t11ZUNpMTYLzi9MTAgwqvFjamc8_RyCcpaEMNF6d9jI=",
         price: 800,
         avg_Rating: 4.78,
         description: "desc",
         arrangements: "Room",
         system: "Milky Way",
         planet: "Jupiter",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Zheng He Station",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         avg_Rating: 4.78,
         arrangements: "Room",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Heleus Cluster",
         planet: "Zheng He",
         region: "Exolayer",
         hostId: 4,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Erikkson Station",
         photos:
           "https://dynaimage.cdn.cnn.com/cnn/q_auto,w_412,c_fill,g_auto,h_232,ar_16:9/http%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F210303175645-space-hotel-voyager-station.jpg https://t4.ftcdn.net/jpg/00/75/70/39/240_F_75703964_rbDXdaldbTTIbRkXjpukZ52hmSRrMJE3.jpg backend/db/images/station3.jpeg",
         price: 570,
         avg_Rating: 4.13,
         arrangements: "Room",
         description: "desc",
         system: "Heleus Cluster",
         planet: "Erikkson",
         region: "Exolayer",
         hostId: 4,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "New Utah",
         photos:
           "https://www.imgbase.info/images/safe-wallpapers/digital_art/sci_fi/62823_sci_fi_futuristic_space_city.jpg https://img.17qq.com/images/qrrreteeqqx.jpeg https://img.17qq.com/images/fjjjpoppgjz.jpeg",
         price: 800,
         avg_Rating: 4.44,
         description: "desc",
         arrangements: "House",
         system: "Heleus Cluster",
         planet: "Pytheas",
         region: "Exolayer",
         hostId: 4,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Tecunis",
         photos:
           "https://d2pn8kiwq2w21t.cloudfront.net/images/jpegPIA24613.width-1600.jpg https://d2pn8kiwq2w21t.cloudfront.net/images/jpegPIA24468.width-1600.jpg https://d2pn8kiwq2w21t.cloudfront.net/images/jpegPIA24470.width-1600.jpg https://d2pn8kiwq2w21t.cloudfront.net/images/jpegPIA24611.width-1600.jpg https://d2pn8kiwq2w21t.cloudfront.net/images/jpegPIA24612.width-1600.jpg ",
         price: 800,
         avg_Rating: 4.78,
         description: "desc",
         system: "Heleus Cluster",
         planet: "Kelun",
         region: "Exolayer",
         hostId: 4,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Forests of Alsages",
         photos:
           "https://i.guim.co.uk/img/media/d143e03bccd1150ef52b8b6abd7f3e46885ea1b3/0_182_5472_3283/master/5472.jpg?width=1200&quality=85&auto=format&fit=max&s=d5a74a011c3fef1ad9c1c962721d221d backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         avg_Rating: 4.78,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Sparta",
         planet: "Alsages",
         region: "Exolayer",
         hostId: 5,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Altaaya Station",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         avg_Rating: 4.78,
         arrangements: "Room",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Sparta",
         planet: "Altaaya",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "North Base",
         photos:
           "https://www.sciencemag.org/sites/default/files/styles/article_main_large/public/images/cc_princess_elisabeth_antarctica_press01_16x9.jpg?itok=5CbwP_mf backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 645,
         avg_Rating: 4.74,
         arrangements: "Room",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Sol",
         planet: "Pluto",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "South Base",
         photos:
           "https://www.telegraph.co.uk/content/dam/science/2017/01/16/unnamed-large_trans_NvBQzQNjv4BqGQR7TMwEvfaYG0TH6J-Ry2g4WxVrb_HQM4PRGLJGkwE-xlarge_trans_NvBQzQNjv4Bq2oUEflmHZZHjcYuvN_Gr-ceALqh55qDyquMVBBBC4CM.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 645,
         avg_Rating: 4.74,
         arrangements: "Room",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Sol",
         planet: "Pluto",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "North Pole",
         photos:
           "https://cdna.artstation.com/p/assets/images/images/006/410/026/large/jun-deng-.jpg?1498400121 backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 500,
         avg_Rating: 4.22,
         arrangements: "Room",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Sol",
         planet: "Mars",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Kaiser Sea",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 1200,
         avg_Rating: 4.52,
         description: "desc",
         arrangements: "House",
         system: "Sol",
         planet: "Mars",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Armstrong Nebula Tour",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 2400,
         avg_Rating: 4.78,
         arrangements: "Spaceship",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Armstrong Nebula",
         planet: "None",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Porolan",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         avg_Rating: 4.78,
         arrangements: "Cabin",
         description: "desc",
         system: "Artemis Tau",
         planet: "Nausica",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Salamis",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         avg_Rating: 4.78,
         arrangements: "Apartment",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Artemis Tau",
         planet: "Salamis",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Asteroid Belt",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 400,
         avg_Rating: 4.51,
         arrangements: "Spaceship",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Artemis Tau",
         planet: "Salamis",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Patavig",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 1100,
         avg_Rating: 3.71,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Artemis Tau",
         planet: "Salamis",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Edolus",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 650,
         avg_Rating: 4.78,
         description: "desc",
         arrangements: "Cabin",
         system: "Sparta",
         planet: "Nausica",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Station Veyaria",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         arrangements: "Cabin",
         avg_Rating: 4.78,
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Hades Gamma",
         planet: "Veyaria",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Utopia",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 1100,
         avg_Rating: 4.98,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Exodus Cluster",
         planet: "Arcadia",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Loki",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 870,
         arrangements: "Cabin",
         avg_Rating: 4.72,
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Asgard",
         arrangements: "Cabin",
         planet: "Loki",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Terra Nova",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         avg_Rating: 4.23,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Asgard",
         planet: "Loki",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Norr",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 400,
         avg_Rating: 3.68,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Asgard",
         planet: "Tyr",
         region: "Exolayer",
         hostId: 6,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Wheeler City",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 800,
         avg_Rating: 4.11,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Serpent Nebula",
         planet: "Boltzmann",
         region: "Exolayer",
         hostId: 7,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Bekenstein Sea",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 1100,
         avg_Rating: 4.29,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Serpent Nebula",
         planet: "Boltzmann ",
         region: "Exolayer",
         hostId: 7,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Saturn City",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 375,
         avg_Rating: 4.09,
         arrangements: "Apartment",
         description: "desc",
         system: "Sol",
         planet: "Saturn",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Beaches of Saturn",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 400,
         avg_Rating: 4.91,
         arrangements: "Cabin",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Sol",
         planet: "Saturn",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Station Excelsior",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 150,
         avg_Rating: 4.4,
         description: "desc",
         system: "Sol",
         planet: "Venus",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
       {
         name: "Element Mines",
         photos:
           "backend/db/images/station1.jpg backend/db/images/station2.jpeg backend/db/images/station3.jpeg",
         price: 75,
         avg_Rating: 3.2,
         arrangements: "Room",
         description:
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

         system: "Sol",
         planet: "Venus",
         region: "Exolayer",
         hostId: 1,
         createdAt: new Date(),
         updatedAt: new Date(),
         latitude: 49.260112287007246,
         longitude: -123.19992906626858,
       },
     ],
     {}
   );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Spots", null, {});
  }
};
